# Generated by Django 5.1 on 2024-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysearch',
            name='temperature',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
